### ISSUE TITLE
snprintf_P is not supported

### ISSUE THREAD

**Issue by brewmanz** [bxparks/EpoxyDuino#33]
snprintf_P is not supported (but vsnprintf_P is).
I fixed this locally by adding a line
```
diff --git a/cores/epoxy/pgmspace.h b/cores/epoxy/pgmspace.h
index 7dc881d..c7635ba 100644
--- a/cores/epoxy/pgmspace.h
+++ b/cores/epoxy/pgmspace.h
@@ -37,6 +37,7 @@
 #define strchr_P strchr
 #define strrchr_P strrchr
 #define memcpy_P memcpy
+#define snprintf_P snprintf
 #define vsnprintf_P vsnprintf
 
 #endif
```

**Comment by bxparks** [comment]
Normally I'd ask for a PR to add any missing compatibility features to EpoxyDuino. But since this is a single line, I'll pick this off the next time I do some work on this project.
