### ISSUE TITLE
Add support for Windows using MINGW32

### ISSUE THREAD

**Issue by MitchBradley** [bxparks/EpoxyDuino#41]
For an application that normally runs on an ESP32, I use EpoxyDuino to run unit tests and for other maintenance tasks on the build host, using platformio's "native" build environment.  It works well when "native" refers to a Linux host, but there are a few issues when "native" is a Windows host compiled via MINGW.  I have a patch to fix these problems, which I will submit as a PR.  I am creating this issue as documentation and explanation of the problems and their solutions.

1. Missing lstat(): lstat() is not defined on some systems. lstat() is like stat() except that, on systems with symlinks, lstat() returns information about the link instead of the referenced file.  Symlinks are not available on some filesystems, notably on earlier Windows versions. Some versions of MINGW do not implement lstat(), leading to complilation failures.  The solution is to use stat() instead of lstat() on systems where lstat() is not available.
2. Missing d_type: In the dirent struct, the d_type field is not always present, even on some POSIX compliant systems (POSIX does not require its presence).  EpoxyFS uses d_type to determine whether a path refers to a directory or regular file. The solution is to check for the presence of d_type and possibly fall back to using lstat() or stat() instad.  It would be possible to use lstat()/stat() in all cases, but d_type is faster on systems that have it.
3. Missing pread()/pwrite(): MINGW does not have pread() and pwrite().  Solution: replace them with lseek() + read()  or lseek() + write() if they are not present.
4. mkdir() arguments: MINGW uses the native Microsoft mkdir() which has one argument instead of POSIX's two.  The second argument is the creation mode, which is meaningless on Windows file systems.  The solution is to use the one-argument form of mkdir() on Windows.
5. main.cpp is Unix-specific: Pretty much everything inside main.cpp is totally Unix specific.  If you define EPOXY_DUINO then the compilation of main.cpp fails on MINGW.  The solution is to add __unix__ to the compilation guard.

With these changes, EpoxyDuino works on Windows under MINGW.

**Comment by bxparks** [comment]
As explained in #42 in more detail, I have concluded that I don't have the bandwidth or desire to support and maintain MINGW within EpoxyDuino. People who are interested in MINGW are more than welcome to maintain a fork of this project. If there are upstream changes which will make that fork easier to maintain, I would be happy to consider those changes.

Closing.
