### ISSUE TITLE
Terminal I/O as under Arduino IDE or terminal emulation program

### ISSUE THREAD

**Issue by felias-fogg** [bxparks/EpoxyDuino#43]
Hi,

I think EpoxyDuino is a terrific thing. Thanks! I recently wrote a few small test sketches to test my debugger and it was great that one could compile them on my Mac as well. However, terminal I/O did not work as expected. Looking into the code, I noticed that the core reads characters only when loop is called. However, there are a lot of programs that have internal loops (such as my small tictactoe program), and for this reason never see any input from the terminal. 

So, I rewrote the read/peek/available to directly call Unix read, which is the most straightforward way, I guess. Well, one needs a one character buffer. I also added a flush to every output character to have the same functionality as in my Arduino sketches.  I'll send you a PR. Perhaps, it is worthwhile to include these changes. 

Best,
Bernhard

**Comment by bxparks** [comment]
Cool, send me the PR and I'll take a look. Implementing the terminal IO emulation in a Unix environment has been tricky. EpoxyDuino was originally intended to handle only the simplest use cases.
